name: Build and push backend to OCIR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short git SHA and tag
        id: vars
        run: |
          shortSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$shortSha" >> $GITHUB_ENV
          echo "IMAGE_TAG=backend-${shortSha}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Get or create OCIR backend repo
        uses: oracle-actions/get-ocir-repository@v1.3.0
        id: get-ocir-repository
        with:
          name: resume
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}

      - name: Log in to OCIR
        uses: oracle-actions/login-ocir@v1.3.0
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Set up ko
        uses: ko-build/setup-ko@v0.9
        env:
          KO_DOCKER_REPO: ${{ steps.get-ocir-repository.outputs.repo_path }}

      - name: Publish image with ko
        env:
          KO_DOCKER_REPO: ${{ steps.get-ocir-repository.outputs.repo_path }}
          IMAGE_TAG: ${{ env.COMMIT_SHORT_SHA }}
        run: |
          ko publish --tags ${IMAGE_TAG} --bare .
